[ci] upload required stemcell if missing before deploy

diff --git a/ci/scripts/test-deployment b/ci/scripts/test-deployment
--- a/ci/scripts/test-deployment
+++ b/ci/scripts/test-deployment
@@ -160,6 +160,37 @@ if [[ "$SKIP_DEPLOY" == "false" ]]; then
 	genesis "do" "${DEPLOY_ENV}" -- list
 	genesis add-secrets "${DEPLOY_ENV}"
 
+	# get and upload stemcell version if needed (handled by bosh cli if version and name are supplied)
+	stemcell_iaas=
+	case "${INFRASTRUCTURE:-none}" in
+		aws)         stemcell_iaas="aws-xen-hvm" ;;
+		azure)       stemcell_iaas="azure-hyperv" ;;
+		openstack)   stemcell_iaas="openstack-kvm" ;;
+		warden)      stemcell_iaas="warden-boshlite" ;;
+		google|gcp)  stemcell_iaas="google-kvm" ;;
+		vsphere)     stemcell_iaas="vsphere-esxi" ;;
+		*)           echo >&2 "Unknown or missing INFRASTRUCTURE value -- cannot upload stemcell" ;;
+	esac
+
+	if [[ -n "$stemcell_iaas" ]] ; then
+		stemcell_data="$(genesis lookup --merged "${DEPLOY_ENV}" stemcells)"
+		stemcell_os="$(jq -r '.[0].os' <<<"$stemcell_data")"
+		stemcell_version="$(jq -r '.[0].version' <<<"$stemcell_data")"
+		stemcell_name="bosh-${stemcell_iaas}-${stemcell_os}-go_agent"
+		upload_options=('--version' "${stemcell_version}" '--name' "$stemcell_name")
+		upload_params="?v=${stemcell_version}"
+		if [[ "$stemcell_version" == "latest" ]] ; then
+			stemcell_version='[0-9]\+\.[0-9]\+'
+			upload_options=()
+			upload_params=""
+		fi
+		if ! genesis bosh "$DEPLOY_ENV" stemcells 2>/dev/null \
+		   | grep "^${stemcell_name}" \
+		   | awk '{print $2}' | sed -e 's/\*//' \
+		   | grep "^${stemcell_version}\$" ; then
+			genesis bosh "$DEPLOY_ENV" upload-stemcell "https://bosh.io/d/stemcells/$stemcell_name${upload_params}" ${upload_options[@]+"${upload_options[@]}"}
+		fi
+	fi
 
 	genesis deploy -y "${DEPLOY_ENV}"
 
